### ISSUE TITLE
Will there be a FirstLang chapter?

### ISSUE THREAD

**Issue by shepherd1530** [ehsanmok/create-your-own-lang-with-rust#20]
Hello there,

I have been reading about Pegs and Inkwell and was glad to discover this book and website. I am curious if the chapter on FirstLang is still on the roadmap? I would be glad to know if publishing it is still part of your plan.

**Comment by ehsanmok** [comment]
Thanks for your interest! It's part of the plan but I'm struggling to find a dedicated time to focus on writing and shaping the way I have in mind so unfortunately I can't make any promises as to when it'll be published.
