### ISSUE TITLE
No method error when building and running tests

### ISSUE THREAD

**Issue by ImVerbatim** [ehsanmok/create-your-own-lang-with-rust#3]
It seems there is a no method error in /calculator/src/compiler/jit.rs on line 39-42 stating that there is  no method for `print_to_string()` for the variable, `function`. `function` is the result of `module.add_function()`. Perhaps this is a matter of using a different version of LLVM? 

**To Reproduce**
Using LLVM version 10.0.0, I simply cloned and ran 
`cargo test --tests`

**Expected behavior**
I expect that all tests pass and I am able to compile and run the program.

**Comment by ImVerbatim** [comment]
For now, I went ahead and changed the line to
`println!("Generated LLVM IR: {:?}", function.get_name().to_str());
`

**Comment by frionx** [comment]
I don't think he works on this project anymore (last commit was in october)

**Comment by ehsanmok** [comment]
Thanks! I'll look into it. There're bunch of things in the pipeline and the progress is slow :)

**Comment by ehsanmok** [comment]
@ImVerbatim cannot replicate this issue locally. Did fresh clone and passed all tests with LLVM 10. Seems [`print_to_string`](https://thedan64.github.io/inkwell/inkwell/values/trait.AnyValue.html#method.print_to_string) is under AnyValue trait now for unification and don't see any issues there.

**Comment by frionx** [comment]
Hey you're back! Will you continue this?

It's an amazing tutorial and I wish you would!

**Comment by ehsanmok** [comment]
Thanks for the support! I'm and there're a lot I want to add and enhance but the progress is slow, given my newborn doesn't leave me any free time 😄

**Comment by ehsanmok** [comment]
Closing the issue for now!
