### ISSUE TITLE
Can i get a pdf of that or any other way.

### ISSUE THREAD

**Issue by shahid777-py** [ehsanmok/create-your-own-lang-with-rust#4]
Awesome book bythe way  i looked upon the website it's an awesome simple explanation , most books and tutorial didn;t do that even if they did they cover up like 700-1000 pages which is so frustrating , i just wanna build a compiler to understand  thats it and you nailed it.

**Comment by ehsanmok** [comment]
Thanks for the encouragement! So glad to hear that 😊 

The PDF should be possible. I'll take a look at the options.

**Comment by shahid777-py** [comment]
> Thanks for the encouragement! So glad to hear that 
> 
> Should be possible to create a PDF of the book content itself though the code part would be separate. Will look at the options.

Well, im looking forward to get a digital even a physical copy because it's worth it. Even though i'm not into rust that much atleast now i don't have any specific purpose, i'm gonna recommend your site not because it's rust based because the compiler construction foundation was explained crystel clear and simple. any one can transform the concept into their own favourite langauge.

**Comment by shahid777-py** [comment]
Can u write something like explaining rust into a lot simpler concise pages , i'm looking but can't get any even the official rust book is heavy, i'm not that into a big huge pages book maybe only for algorithms, but langauge book has to simple not to make afraid the introductory user by the humangous size. I know rust is also becoming so Huge like C++, so lot of thing needs to be there but can u create something like what is necassary and needed for a novice user about rust , i know u can do it . I like books like The K&R that book is compact and straight to the point.

**Comment by shahid777-py** [comment]
One more thing can u explain how the bytecode gets executed in the VM if its `implementation independent/Architecture i`ndeepdendent.I havn't read your book entirely,

I heard that `Bytecode` gets executed in the `VM` and it's also architecture independent correct me if am wrong, however lets say the bytecode is a wrapper around opcode or binary , so it's still needs to be executed that means it should be executed in the machine instruction and the machine instruction depends on the Vendor and other stuffs right.

Maybe All the Architecture specific instructions `binded ` into the `VM` so the VM will execute based on Your system architecture, Am i right or wrong , Please teach me.

**Comment by ehsanmok** [comment]
Sorry for my late reply! Given the current scope I have in mind it'll be infeasible to not assume some Rust knowledge. There's already the official book for that. For the PDF, I thought about it but ATM I don't want to export the content out. Maybe when I release the first edition or so. I'll have it in my mind. Thanks for your interests!
